version: '3'

services:
  php:
    volumes:
      - ../src:/var/www/html
      - ../php.ini:/usr/local/etc/php/php.ini
      - ../sites-available:/etc/apache2/sites-available
    ports:
      - ${PHP_PORT}:80
    build:
      context: ./php-apache
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:10.4.12
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:5.0.7
    ports:
      - ${REDIS_PORT}:6379
    restart: always
  adminer:
    image: adminer:4.7.6
    ports:
      - ${ADMINER_PORT}:8080
    restart: always
volumes:
  mysql-data: