version: '3'

services:
  php:
    ports:
      - ${PHP_PORT}:80
    build:
      context: ./php-apache
    depends_on:
      - db
  db:
    image: mariadb:10.4.12
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
  adminer:
    image: adminer:4.7.6
    ports:
      - ${ADMINER_PORT}:8080